name: ovrCaffeinatd
favicon: null
layout_spectrum: 0.8419674166943878
typography_spectrum: 0.6958424865733832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06995808612555265
  lightness: 0.3230337903369218
  saturation: 0.2242692473810166
  rhythmicContrast: 0.4682444352656603
purpose: []
